#!/bin/sh

PATHSCRIPT="${0%/*}"
echo $PATHSCRIPT

if [ -e $PATHSCRIPT/AI-FOIL.jar ]
then
	# Droit d'exécution
	chmod u+x $PATHSCRIPT/AI-FOIL.jar
else
	echo "JAR AI-FOIL introuvable dans le répertoire $PATHSCRIPT"
fi

if [ -e $PATHSCRIPT/ai-foil-jar ]
then
	# Droit d'exécution
	chmod u+x $PATHSCRIPT/ai-foil-jar
else
	echo "Script ai-foil_jar introuvable dans le répertoire $PATHSCRIPT" 
fi
